language: node_js
sudo: false
node_js:
- 4
- 6
- 8
script:
- npm run clean
- npm run build
- npm run lint
- npm test
deploy:
  provider: npm
  email: hello@brianneisler.com
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: brianneisler/firedex
