language: node_js
sudo: false
node_js:
- 4
- 6
- 8
script:
- npm run clean
- npm run build
- npm run lint
- npm test
deploy:
  provider: npm
  email: hello@brianneisler.com
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: brianneisler/firedex
  api_key:
    secure: vSn42ybZhoDtE5bn/U2SBj9BLBZId+6h586TlFsCGQGIeyz+9f2L30zAIWyqF+P0XBLbZKSF5vwblPCzrsBeIH+YiyOQbqghTujFXe5T7R5W2GD/cRRZLV2Fot6keJVwG5S+jH59oTo/3t5jzBbRFnVmyWhqtt49pTkaoKSz6ErojL6iL7RusvwIMOep5tmjQGZtkVbt7i3Whje7DmmYSF8vRX8Qu7l1u5IO9WbJpQIA1JKVf7mRRjFNkRJOIR1aNPcxAZSZXAPW0Qd/OSlipV6b8gVNLXFYmnz8i9MWdq1U8831VkydWMspKBEkYbod7FLjTKQTAFW6YXVvphI6TFwYieN11Y0PNnvrckbru04/A9P3Ml35mLiCMIvN1uTBvCVQaBVrYywef8lvs6m3cS5R3A9lG4jO0Ev7oe8bpCgff04Kb1QvFaT+X+g0nGnPMeKqXl+wmj4+3C9PDWD1bG2HxmSc3TlNN8ojQnoRUn597uNgJx5gY1bxQHGIYDVhAVhhgr4gi2sYHojf23IVPIgfNAaCQtQqneMCp2L2GNdAkcwSckw64oFdbqx8DbHH3VBo9geUfHvwkQ9dEKmx8tY3OYIYHeXAKv+1ApXBgMTSAm/hT3l0wVi85svHhaU2naMYRTmbzQNTvq+G6Z5Nd6iguTLA276eNQxxzUiCAEc=
